### ISSUE TITLE
NO Match in orgList for XXXXX.onmicrosoft.com

### ISSUE THREAD

**Issue by markushartmann-dev** [TS-Steff/PRTG-Veeam-MS365-Tenant#1]
Hi there, thanks for updating this PRTG script for Veeam M365 V8 - even after the new version, i get the following errors:

> PS C:\Users\Administrator\Downloads> & '.\PRTG-veeam-backup-MS365-tenant.ps1' -apiUrl "https://srv-veeam-365.XXXXXXXXX:4443/" -username "localhost\administrator" -password "XXXXXXXXX" -orgName "XXXXXXXXX.onmicrosoft.com" -ignoreSSL "true"
C:\Users\Administrator\Downloads\PRTG-veeam-backup-MS365-tenant.ps1 : Error invoking web request at Start
In Zeile:1 Zeichen:1
+ & '.\PRTG-veeam-backup-MS365-tenant.ps1' -apiUrl "https://srv-veeam-3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PRTG-veeam-backup-MS365-tenant.ps1

C:\Users\Administrator\Downloads\PRTG-veeam-backup-MS365-tenant.ps1 : Error authentication result
In Zeile:1 Zeichen:1
+ & '.\PRTG-veeam-backup-MS365-tenant.ps1' -apiUrl "https://srv-veeam-3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PRTG-veeam-backup-MS365-tenant.ps1

ConvertFrom-Json : Ungültiger JSON-Primitiv: .
In C:\Users\Administrator\Downloads\PRTG-veeam-backup-MS365-tenant.ps1:150 Zeichen:33
+     $orgsObj = $jsonResultOrg | ConvertFrom-Json
+                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**NO Match in orgList for XXXXXXXXX.onmicrosoft.com**

The password is correct, the account for testing this script in VBO365 is marked as a service-account (so no MFA is needed). On the same machine and version 7, everythin was running fine.
I have the same problem on 3 different environments.
Can also provide you with more informations, if you need so.

Cheers.

**Comment by TS-Steff** [comment]
Hi Markus

Thank you for your feedback.

The parameter -orgName does have to be exactley like the Organizations in Veeam Backup for Microsoft 365.

I have modified the debug output. Please run the script with -debug $true and have a look for `*** ALL ORG NAMES ***`. After this is a list with all orgNames the script found.

This Output is directly before `NO Match in orgList for XXXXX.onmicrosoft.com`. Is the org listed there?

Cheers.

**Comment by TS-Steff** [comment]
@markushartmann-dev 
I've just added an additional parameter to list all orgs on the server.

`& '.\PRTG-veeam-backup-MS365-tenant.ps1' -apiUrl "https://srv-veeam-365.xxxxxxxxx:4443/" -username "localhost\administrator" -password "XXXXXXXXX" -orgName "XXXXXXXXX.onmicrosoft.com" -ignoreSSL "true" -listOrgs $true`

this will output a list with all orgs on the server. hope this helps

**Comment by markushartmann-dev** [comment]
Thanks for providing more infos and the debug option.
Unfortunately i think something is missing on my side:

![image](https://github.com/user-attachments/assets/ed926fb2-5ad3-4199-b9fb-52b3440d4456)

and with activated debug:
![image](https://github.com/user-attachments/assets/d644e30f-b545-4b97-81d1-4c7eb6da3046)

thank you so much for your help.
Cheers, Markus

**Comment by TS-Steff** [comment]
Mine is running on 4443 to. Typo in the readme 🤣 (changed now)

can you open https://srv-veeam-365.xxxxxxxxx:4443/swagger/ui/index/index.html

**Comment by markushartmann-dev** [comment]
jepp, this is working: 
![image](https://github.com/user-attachments/assets/ad1c68b6-614c-4310-bc9f-35d1f4416ab7)

**Comment by TS-Steff** [comment]
I think i found the problem
`-apiUrl "https://srv-veeam-365.xxxxxxxxx:4443/"` has an ending slash. Without this it sould work
`-apiUrl "https://srv-veeam-365.xxxxxxxxx:4443"`

**Comment by markushartmann-dev** [comment]
omg, sometimes it could be so simple :-)
Thank you so much! It's working - made my day <3

**Comment by TS-Steff** [comment]
Great

**Comment by TS-Steff** [comment]
@markushartmann-dev 
Just for curiosity. What Windows Version do you use?

**Comment by markushartmann-dev** [comment]
Windows Server 2019 on this environment
